### PR TITLE
Removed 'partners' as few other .json files had 'partners' in them.

### PR DESCRIPTION
**Pull request by mbermanarl**
Thanks for submitting a pull request! Below are a few things you can do to help us more quickly review your changes.

## Checklist

I have…

- [x] run the application locally (`./scripts/serve`) and verified that my changes behave as expected.
- [x] run the build process locally (`./scripts/build`) and make sure it builds correctly.
- [x] run the test suite (`./scripts/test`) and verified that all tests pass.
- [x] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [ ] thoroughly outlined below the steps necessary to test my changes.
- [ ] attached screenshots illustrating relevant behavior before and after my changes.
- [ ] read, understand, and agree to the terms described in [CONTRIBUTING.md](../CONTRIBUTING.md).
- [ ] added my name, email address, and copyright date to [CONTRIBUTORS.md](../CONTRIBUTORS.md).

## Summary of Changes

This pull request…

- _Summarize change number one._
- _Summarize change number two._
- _etc. etc. etc._

## Testing

To verify the changes proposed in this pull request…

1. _Describe testing step one._
1. _Describe testing step two._
1. _etc. etc. etc._

## Screenshots

_Attach relevant before and after screenshots here._

### CODE REVIEW

**Comment by jordangov** [comment]
Heh... fun story, I have a separate PR in for this field because it doesn't follow the proper code.gov format. Would you rather fix it or remove it?

**Comment by mbermanarl** [comment]
May as well remove it to be consistent with all the other projects.  I don't have email addresses for the organizations either.

-Morris Berman
 (morris.s.berman.civ@mail.mil)

Morris Berman
(301)394-4188 (V, ALC)
(301)873-7975 (Mobile)
(301)394-1801 (FAX)

U.S. Army Research Laboratory
ATTN: FCDD-RLS-DP (Power Conditioning Branch) (Morris Berman)
2800 Powder Mill Road        
Adelphi, Maryland 20783-1145


-----Original Message-----

**Comment by jordangov** [comment]
Don't worry about consistency, be a trend setter! The field exists in the schema for a reason. :)

That said, happy to remove it if you want.

**Comment by mbermanarl** [comment]
I don't want to be the nail that sticks up and gets hammered back down! :-)
I'm good with removal.

-Morris Berman
 (morris.s.berman.civ@mail.mil)

Morris Berman
(301)394-4188 (V, ALC)
(301)873-7975 (Mobile)
(301)394-1801 (FAX)

U.S. Army Research Laboratory
ATTN: FCDD-RLS-DP (Power Conditioning Branch) (Morris Berman)
2800 Powder Mill Road        
Adelphi, Maryland 20783-1145


-----Original Message-----

**Pull request merged**
