### PR TITLE
Add dds.mil and correct typo. Links to  #245

### PR DESCRIPTION
**Pull request by milovanderlinden**
## Approach

- fixed a little typo in the file at `src\github.com\Code-dot-mil\code.mil.json`
- copied code.mil.json to `src\github.com\DDS-dot-mil\DDS.mil.json`
- Looked at the date of the first and last commit for the dds.mil repository
- Copied the description of the dds.mil repository
- Changed values so it reflects the dds.mil repository as requested.

Please review.

### CODE REVIEW

**Comment by milovanderlinden** [comment]
Hi @jordangov I added my name to the contributors list, the change to the file is added to this PR.

**Comment by jordangov** [comment]
Thanks for adding your name to the contributors! But it looks like you've checked in the full, built code.json file, changed the version of Ruby we're using, and changed the styles for those button links in the same commit. :/

Can we revert those other changes? They really aren't part of the same PR.

**Comment by milovanderlinden** [comment]
Oops! That was wrong. I reverted that commit and replaced it with a change to `CONTRIBUTORS.md` only

**Comment by milovanderlinden** [comment]
By the way, your comments are highly valued by me. Just to let you know I appreciate that you take time to really look at the code and test my changes.

**Pull request merged**
