### PR TITLE
[HOLD] Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by heatherdesigns**
Prepare for submission of pull request by updating CONTRIBUTORS.md

Thanks for submitting a pull request! Below are a few things you can do to help us more quickly review your changes.

## Checklist

I have…

- [ ] ~~run the application locally (`./scripts/serve`) and verified that my changes behave as expected.~~
- [ ] ~~run the build process locally (`./scripts/build`) and make sure it builds correctly.~~
- [ ] ~~run the test suite (`./scripts/test`) and verified that all tests pass.~~
- [ ] ~~summarized below my changes and noted which issues (if any) this pull request fixes or addresses.~~
- [ ] ~~thoroughly outlined below the steps necessary to test my changes.~~
- [ ] ~~attached screenshots illustrating relevant behavior before and after my changes.~~
- [x] read, understand, and agree to the terms described in [CONTRIBUTING.md](../CONTRIBUTING.md).
- [x] added my name, email address, and copyright date to [CONTRIBUTORS.md](../CONTRIBUTORS.md).

## Summary of Changes

This pull request…

- _Updates CONTRIBUTORS.md with a new contributor._

### CODE REVIEW

**Comment by jordangov** [comment]
Hi @heatherdesigns! Thanks for this. You can actually just include this change with your first, full PR. If you want, we can leave this PR open and you can just add commits as you get to them. Sound ok?

**Comment by heatherdesigns** [comment]
@jordangov Awesome ~ Thank you! :smile:

**Comment by heatherdesigns** [comment]
@jordangov This is ready for review. :smile:

Thanks!
Heather

**Comment by jordangov** [comment]
Sorry for the delay! And thanks for re-merging master back in. This looks good to me.

**Pull request merged**
