### PR TITLE
Shiva

### PR DESCRIPTION
**Pull request by elfmaster**
Thanks for submitting a pull request! Below are a few things you can do to help us more quickly review your changes.

## Checklist

I have…

- [N ] run the application locally (`./scripts/serve`) and verified that my changes behave as expected.
- [N ] run the build process locally (`./scripts/build`) and make sure it builds correctly.
- [N ] run the test suite (`./scripts/test`) and verified that all tests pass.
- [Y ] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [N/A ] thoroughly outlined below the steps necessary to test my changes.
- [N/A] attached screenshots illustrating relevant behavior before and after my changes.
- [ Y] read, understand, and agree to the terms described in [CONTRIBUTING.md](../CONTRIBUTING.md).
- [ Y] added my name, email address, and copyright date to [CONTRIBUTORS.md](../CONTRIBUTORS.md).

NOTE: I've been having Ruby compatibility issues preventing me from getting the site working correctly.
I am nonetheless fairly confident that the json file I added is correct. I am concerned about making sure Shiva is open sourced by August 12th (DEFCON talk).

## Summary of Changes

This pull request…

Simply adds the shiva.json file, and my information to the CONTRIBUTORS.md list.

## Testing
N/A

## Screenshots

N/A

### CODE REVIEW

**Comment by david-saeger** [comment]
hello @elfmaster . Can you confirm that this project was created on behalf of the Department of Defense? I tried emailing, check your spam folder?

**Comment by elfmaster** [comment]
Good morning. The project was invented 2yrs ago. The last year of Shiva
development was formed from the DARPA AMP program.

-Ryan

**Comment by david-saeger** [comment]
Is there a COR or somebody with a .mil email address familiar with this
project you can put me in touch with to confirm?

**Comment by elfmaster** [comment]
Sure, shoot me an email to elfmaster@arcana-research.io

**Review by david-saeger — APPROVED** [review]

**Pull request merged**
