### PR TITLE
Move tfstate to remote

### PR DESCRIPTION
**Pull request by arichiv**
Right now the terraform state file is stored in github. It's better practice to store the state in s3 and the config in github

### CODE REVIEW

**Comment by jordangov** [comment]
Don't really know what this PR is for... can you add a description of what and why? How is tfstate remote? Also... do we want to do this if we end up moving to Netlify?

**Comment by arichiv** [comment]
@jordangov if we do move to netlify, this change is minor

Added description, sorry for not adding that before!

**Pull request merged**
